import asyncio

from app.ai.provider import LMStudioProvider, LLMGenerationRequest


class FakeStreamResponse:
    def __init__(self, lines):
        self._lines = lines

    async def __aenter__(self):
        return self

    async def __aexit__(self, exc_type, exc, tb):
        return False

    def raise_for_status(self):
        return None

    async def aiter_lines(self):
        for line in self._lines:
            yield line


class FakeResponse:
    def __init__(self, payload):
        self._payload = payload

    def raise_for_status(self):
        return None

    def json(self):
        return self._payload


class FakeAsyncClient:
    def __init__(self, *args, **kwargs):
        pass

    async def __aenter__(self):
        return self

    async def __aexit__(self, exc_type, exc, tb):
        return False

    async def post(self, url, json, headers):
        return FakeResponse(
            {
                "choices": [
                    {
                        "message": {
                            "content": "Generated by LM Studio",
                        }
                    }
                ]
            }
        )

    def stream(self, method, url, json, headers):
        return FakeStreamResponse(
            [
                'data: {"choices":[{"delta":{"content":"Hello "}}]}',
                'data: {"choices":[{"delta":{"content":"world"}}]}',
                "data: [DONE]",
            ]
        )


def test_lm_studio_provider_parses_generate_and_stream(monkeypatch):
    monkeypatch.setattr("app.ai.provider.httpx.AsyncClient", FakeAsyncClient)

    provider = LMStudioProvider(
        base_url="http://127.0.0.1:1234/v1", model_name="qwen2.5-3b-instruct"
    )
    request = LLMGenerationRequest(
        action_type="rewrite",
        prompt="Rewrite this text",
        source_text="Rewrite this text",
        context_excerpt="",
        instruction="",
        options={},
    )

    async def run():
        generated = await provider.generate(request)
        streamed_chunks = [chunk async for chunk in provider.stream(request)]
        return generated, streamed_chunks

    generated, streamed_chunks = asyncio.run(run())
    assert generated == "Generated by LM Studio"
    assert "".join(streamed_chunks) == "Hello world"
